### ISSUE TITLE
Add a getter for an array of tokens held by an owner

### ISSUE THREAD

**Issue by chebykin** [OpenZeppelin/openzeppelin-solidity#1512] opened 2018-11-23 16:52 UTC
## Problem
I want to inherit `ERC721Full.sol` contract and add an extra getter for an array of tokens held by a given user.

## Expected behaviour
In previous versions it was possible by adding an extra function and accessing an `internal` `_ownedTokens` mapping:
````solidity
function tokensOfOwner(address _owner) external view returns (uint256[]) {
    return ownedTokens[_owner];
}
````

## Current behaviour
In version 2.x it is impossible to access a `private` `_ownedTokens` mapping.

**Comment by chebykin** [comment] 2018-11-24 11:46
Thank you! Will wait for this feature.

**Comment by nventuro** [comment] 2018-11-24 14:45
Isn't this a duplicate of https://github.com/OpenZeppelin/openzeppelin-solidity/issues/1102?

**Comment by frangio** [comment] 2018-11-24 17:10
Hm, that issue is about an external interface, this one is about an internal one for extension purposes.

**Comment by Aniket-Engg** [comment] 2018-11-27 06:47
shouldn't `uint256[] storage` be `uint256[] memory`?

**Comment by frangio** [comment] 2018-11-27 15:24
@Aniket-Engg I think it should be `storage` because the function would be returning a pointer to the array that is held in storage. Copying the array to memory would be very expensive unnecessarily IMO.

**Closed** 2018-12-05 20:45 UTC
Labels: area:contracts, kind:feature

**Comment by imsys** [comment] 2022-01-12 22:36
For some reason this was removed on https://github.com/OpenZeppelin/openzeppelin-contracts/commit/bd0778461da82364aebd2d763bb338795c5f9fa7

**Comment by Nunnaphat1234** [comment] 2022-05-15 11:27
Hello, I would like to contact your team directly with honesty. I sold my car and house and invested in my portfolio. My account has few assets. I have a problem with translation. I want my money back, can I withdraw?GNOSIS Chain  Come check my account Is my money safe? My email address.ladbli25@gmail.com

**Comment by arzusa** [comment] 2022-07-15 16:17
> I think we could add an internal function in `ERC721Enumerable` for this.
> 
> ```solidity
> function _tokensOfOwner(address owner) internal view returns (uint256[] storage) {
>     return _ownedTokens[owner];
> }
> ```
not work

TypeError: Return argument type mapping(uint256 => uint256) is not implicitly convertible to expected type (type of first return variable) uint256[] storage pointer.
