### ISSUE TITLE
Role implementations allow to renounce own role even if it the last address with this role.

### ISSUE THREAD

**Issue by bashalex** [OpenZeppelin/openzeppelin-solidity#1489] opened 2018-11-01 12:14 UTC
Current role implementations do not forbid renouncing of own role in case there are no more addresses with the same role. Considering the `onlyRole` modifier in the `addRole(address account)`  functions, there is a possibility to stuck in a situation when there are no more roles left. I'd propose to add an additional check to the `remove()` function of the [Roles](https://github.com/OpenZeppelin/openzeppelin-solidity/blob/master/contracts/access/Roles.sol) library ensuring that there is at least one address with an assigned role left.

**Comment by bashalex** [comment] 2018-11-14 15:57
@nventuro since you commented on a Roles-related issue earlier, could you give some feedback on this one as well?

**Comment by frangio** [comment] 2018-11-15 20:50
Thanks for the suggestion @bashalex! This is actually by design, though. The situation where there are no more accounts assigned to a role is sometimes desirable. The typical example is a centralized minting scheme where at some point minters may want to guarantee token holders that the supply is final.

**Comment by bashalex** [comment] 2018-11-15 23:04
@frangio Agreed. However, if a role used for some sort of a "traditional" owner replacement, a simple human mistake may ruin the contract leaving it without any "owners".

**Comment by talasa** [comment] 2018-11-19 17:03
I suggest making "remove" safer by blocking requests to remove the last account.
For making it possible to remove all roles (which is sometimes desirable) there are a few options:
1. Adding a new function "removeLast". So it won't happen by accident.
2. Leaving it as-is and let the users find a way to achieve that functionality. For example add Role to a non-upgradable contract address that does not have the capability to call the relevant current contract functions.

**Comment by bashalex** [comment] 2018-11-20 11:46
I like the idea with `removeLast()`. It sounds like it solves both problems. @frangio?

**Comment by nventuro** [comment] 2019-05-24 23:57
While interesting, there are many situations when it is contracts that have the role, and adding this would mean that they'd have to do a sort of try/catch attempt, calling `removeLast` if the first call fails, which makes the whole thing superfluous. Additionally, this would require `Roles` being aware of how many accounts have the role, and it currently lacks this capability (see #1602).

**Closed by nventuro** 2019-05-24 23:57 UTC
