### ISSUE TITLE
I would love to see a thoroughly audited SafeMath file for signed integers.

### ISSUE THREAD

**Issue by MicahZoltu** [OpenZeppelin/openzeppelin-solidity#349] opened 2017-08-03 21:29 UTC
I believe signed integers have a different set of problems from unsigned integers when it comes to safe math operations.  I would love to see a thoroughly thought through and audited version of SafeMath.sol but for signed numbers.

**Comment by elopio** [comment] 2018-05-11 04:09
Duplicate of #705. Thanks for the report @MicahZoltu!

**Closed by elopio** 2018-05-11 04:09 UTC
Labels: backlog, feature
